//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INetSales.OnlineInterface.inet.integratornet.com.br {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "4.0.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="IntegraWSPortBinding", Namespace="http://webservice.myse.com.br/")]
    public partial class IntegraWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public IntegraWS() {
            this.Url = "http://inet.integratornet.com.br:8080/1.5/IntegraWS";
        }
        
        public IntegraWS(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setProduto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setProduto", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetProduto(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setProduto", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetProduto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string deletaPrecoProduto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("deletaPrecoProduto", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindeletaPrecoProduto(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("deletaPrecoProduto", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EnddeletaPrecoProduto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setEstoquePreco([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setEstoquePreco", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetEstoquePreco(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setEstoquePreco", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetEstoquePreco(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setPromocao([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setPromocao", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetPromocao(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setPromocao", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetPromocao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setContas([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setContas", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetContas(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setContas", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetContas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setVendedor([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setVendedor", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetVendedor(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setVendedor", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetVendedor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setCategoria([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setCategoria", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetCategoria(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setCategoria", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetCategoria(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setCondicaoPagamento([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setCondicaoPagamento", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetCondicaoPagamento(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setCondicaoPagamento", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetCondicaoPagamento(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setTabelaPreco([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setTabelaPreco", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetTabelaPreco(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setTabelaPreco", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetTabelaPreco(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setStatCliente([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setStatCliente", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetStatCliente(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setStatCliente", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetStatCliente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setStatClienteProduto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setStatClienteProduto", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetStatClienteProduto(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setStatClienteProduto", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetStatClienteProduto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setPreco([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setPreco", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetPreco(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setPreco", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetPreco(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string login([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("login", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginlogin(string xml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("login", new object[] {
                        xml}, callback, asyncState);
        }
        
        /// <remarks/>
        public string Endlogin(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setPacoteNota([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("setPacoteNota", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetPacoteNota(string xml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setPacoteNota", new object[] {
                        xml}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetPacoteNota(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consultaProcessamentoNFePedido([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("consultaProcessamentoNFePedido", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginconsultaProcessamentoNFePedido(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultaProcessamentoNFePedido", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndconsultaProcessamentoNFePedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getBoleto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("getBoleto", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetBoleto(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getBoleto", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetBoleto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getIDUltimoCupomFiscal([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("getIDUltimoCupomFiscal", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetIDUltimoCupomFiscal(string xml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getIDUltimoCupomFiscal", new object[] {
                        xml}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetIDUltimoCupomFiscal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getPacoteEstoque([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("getPacoteEstoque", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPacoteEstoque(string xml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPacoteEstoque", new object[] {
                        xml}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPacoteEstoque(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getPreco([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("getPreco", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPreco(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPreco", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPreco(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getProduto([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("getProduto", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetProduto(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getProduto", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetProduto(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getProdutoNovo([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("getProdutoNovo", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetProdutoNovo(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getProdutoNovo", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetProdutoNovo(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCliente([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("getCliente", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCliente(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCliente", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCliente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setPedido([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("setPedido", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetPedido(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setPedido", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setStatusPedido([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("setStatusPedido", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetStatusPedido(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setStatusPedido", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetStatusPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setPedidoSincronizado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("setPedidoSincronizado", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetPedidoSincronizado(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setPedidoSincronizado", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetPedidoSincronizado(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setLevantamentoPedidoSincronizado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("setLevantamentoPedidoSincronizado", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetLevantamentoPedidoSincronizado(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setLevantamentoPedidoSincronizado", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetLevantamentoPedidoSincronizado(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getPedido([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getPedido", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetPedido(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getPedido", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getLevantamentoEstoquePedido([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getLevantamentoEstoquePedido", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetLevantamentoEstoquePedido(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getLevantamentoEstoquePedido", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetLevantamentoEstoquePedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setCliente([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCliente) {
            object[] results = this.Invoke("setCliente", new object[] {
                        xmlCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetCliente(string xmlCliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setCliente", new object[] {
                        xmlCliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetCliente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setMixCliente([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCliente) {
            object[] results = this.Invoke("setMixCliente", new object[] {
                        xmlCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetMixCliente(string xmlCliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setMixCliente", new object[] {
                        xmlCliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetMixCliente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getUsuario", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetUsuario(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getUsuario", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetUsuario(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCondicaoPagamento([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getCondicaoPagamento", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCondicaoPagamento(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCondicaoPagamento", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCondicaoPagamento(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getRamoNegocio([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getRamoNegocio", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRamoNegocio(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRamoNegocio", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRamoNegocio(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getRoteiro([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getRoteiro", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRoteiro(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRoteiro", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRoteiro(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getRemessa([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getRemessa", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRemessa(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRemessa", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRemessa(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setLatitudeLongitudeVendedor([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("setLatitudeLongitudeVendedor", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetLatitudeLongitudeVendedor(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setLatitudeLongitudeVendedor", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetLatitudeLongitudeVendedor(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCategoria([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getCategoria", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCategoria(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCategoria", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCategoria(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCidade([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getCidade", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCidade(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCidade", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCidade(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getFechamentos([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getFechamentos", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetFechamentos(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getFechamentos", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetFechamentos(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getCupomFiscalAguardandoImpressao([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getCupomFiscalAguardandoImpressao", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetCupomFiscalAguardandoImpressao(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getCupomFiscalAguardandoImpressao", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetCupomFiscalAguardandoImpressao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getItensPedidoAguardandoImpressao([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getItensPedidoAguardandoImpressao", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetItensPedidoAguardandoImpressao(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getItensPedidoAguardandoImpressao", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetItensPedidoAguardandoImpressao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getImpressoraTicket([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getImpressoraTicket", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetImpressoraTicket(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getImpressoraTicket", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetImpressoraTicket(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getImpressoraTicketETPImpressao([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("getImpressoraTicketETPImpressao", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetImpressoraTicketETPImpressao(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getImpressoraTicketETPImpressao", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetImpressoraTicketETPImpressao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setOportunidade([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlOportunidade) {
            object[] results = this.Invoke("setOportunidade", new object[] {
                        xmlOportunidade});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetOportunidade(string xmlOportunidade, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setOportunidade", new object[] {
                        xmlOportunidade}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetOportunidade(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string isCPF_CNPJCadastrado([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCliente) {
            object[] results = this.Invoke("isCPF_CNPJCadastrado", new object[] {
                        xmlCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginisCPF_CNPJCadastrado(string xmlCliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("isCPF_CNPJCadastrado", new object[] {
                        xmlCliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndisCPF_CNPJCadastrado(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setVisita([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCliente) {
            object[] results = this.Invoke("setVisita", new object[] {
                        xmlCliente});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetVisita(string xmlCliente, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setVisita", new object[] {
                        xmlCliente}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetVisita(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setDTUltimaSincronizacao([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlUsuario) {
            object[] results = this.Invoke("setDTUltimaSincronizacao", new object[] {
                        xmlUsuario});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetDTUltimaSincronizacao(string xmlUsuario, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setDTUltimaSincronizacao", new object[] {
                        xmlUsuario}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetDTUltimaSincronizacao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getDTUltimaSincronizacao([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xml) {
            object[] results = this.Invoke("getDTUltimaSincronizacao", new object[] {
                        xml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetDTUltimaSincronizacao(string xml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getDTUltimaSincronizacao", new object[] {
                        xml}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetDTUltimaSincronizacao(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setCupomFiscal([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCupomfiscal) {
            object[] results = this.Invoke("setCupomFiscal", new object[] {
                        xmlCupomfiscal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetCupomFiscal(string xmlCupomfiscal, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setCupomFiscal", new object[] {
                        xmlCupomfiscal}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetCupomFiscal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cancelaCupomFiscal([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCancelamentoCupomfiscal) {
            object[] results = this.Invoke("cancelaCupomFiscal", new object[] {
                        xmlCancelamentoCupomfiscal});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincancelaCupomFiscal(string xmlCancelamentoCupomfiscal, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("cancelaCupomFiscal", new object[] {
                        xmlCancelamentoCupomfiscal}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndcancelaCupomFiscal(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool setCupomFiscalImpresso([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCupomfiscal) {
            object[] results = this.Invoke("setCupomFiscalImpresso", new object[] {
                        xmlCupomfiscal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetCupomFiscalImpresso(string xmlCupomfiscal, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setCupomFiscalImpresso", new object[] {
                        xmlCupomfiscal}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndsetCupomFiscalImpresso(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool setItemCupomFiscalImpresso([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlCupomfiscal) {
            object[] results = this.Invoke("setItemCupomFiscalImpresso", new object[] {
                        xmlCupomfiscal});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetItemCupomFiscalImpresso(string xmlCupomfiscal, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setItemCupomFiscalImpresso", new object[] {
                        xmlCupomfiscal}, callback, asyncState);
        }
        
        /// <remarks/>
        public bool EndsetItemCupomFiscalImpresso(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getProdutoPesquisa([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("getProdutoPesquisa", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetProdutoPesquisa(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getProdutoPesquisa", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetProdutoPesquisa(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getVisita([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("getVisita", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetVisita(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getVisita", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetVisita(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getRelatorioPedido([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("getRelatorioPedido", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRelatorioPedido(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRelatorioPedido", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRelatorioPedido(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getRelatorioFaturamentoProdutoPorCategoria([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("getRelatorioFaturamentoProdutoPorCategoria", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRelatorioFaturamentoProdutoPorCategoria(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRelatorioFaturamentoProdutoPorCategoria", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRelatorioFaturamentoProdutoPorCategoria(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string getRelatorioContas([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlPedido) {
            object[] results = this.Invoke("getRelatorioContas", new object[] {
                        xmlPedido});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegingetRelatorioContas(string xmlPedido, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("getRelatorioContas", new object[] {
                        xmlPedido}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndgetRelatorioContas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://webservice.myse.com.br/", ResponseNamespace="http://webservice.myse.com.br/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string setRota([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string xmlProduto) {
            object[] results = this.Invoke("setRota", new object[] {
                        xmlProduto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginsetRota(string xmlProduto, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("setRota", new object[] {
                        xmlProduto}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndsetRota(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }
    }
}
