#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("INetSales.AndroidUi.Resource", IsApplication=true)]

namespace INetSales.AndroidUi
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f060000
			public const int tipo_pagamento_array = 2131099648;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010005
			public const int centered = 2130771973;
			
			// aapt resource value: 0x7f01000d
			public const int clipPadding = 2130771981;
			
			// aapt resource value: 0x7f010006
			public const int fillColor = 2130771974;
			
			// aapt resource value: 0x7f01000e
			public const int footerColor = 2130771982;
			
			// aapt resource value: 0x7f010011
			public const int footerIndicatorHeight = 2130771985;
			
			// aapt resource value: 0x7f010010
			public const int footerIndicatorStyle = 2130771984;
			
			// aapt resource value: 0x7f010012
			public const int footerIndicatorUnderlinePadding = 2130771986;
			
			// aapt resource value: 0x7f01000f
			public const int footerLineHeight = 2130771983;
			
			// aapt resource value: 0x7f010013
			public const int footerPadding = 2130771987;
			
			// aapt resource value: 0x7f010008
			public const int orientation = 2130771976;
			
			// aapt resource value: 0x7f010007
			public const int pageColor = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int radius = 2130771977;
			
			// aapt resource value: 0x7f010015
			public const int selectedBold = 2130771989;
			
			// aapt resource value: 0x7f010014
			public const int selectedColor = 2130771988;
			
			// aapt resource value: 0x7f01000a
			public const int snap = 2130771978;
			
			// aapt resource value: 0x7f01000b
			public const int strokeColor = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int strokeWidth = 2130771980;
			
			// aapt resource value: 0x7f010016
			public const int textColor = 2130771990;
			
			// aapt resource value: 0x7f010017
			public const int textSize = 2130771991;
			
			// aapt resource value: 0x7f010018
			public const int titlePadding = 2130771992;
			
			// aapt resource value: 0x7f010019
			public const int topPadding = 2130771993;
			
			// aapt resource value: 0x7f010000
			public const int vpiCirclePageIndicatorStyle = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int vpiPageTheme = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int vpiTabPageIndicatorStyle = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int vpiTabTextStyle = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int vpiTitlePageIndicatorStyle = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int default_circle_indicator_centered = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int default_circle_indicator_snap = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int default_title_indicator_selected_bold = 2131230722;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040006
			public const int background_line_default = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int custom_theme_color = 2130968583;
			
			// aapt resource value: 0x7f040012
			public const int default_circle_indicator_fill_color = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int default_circle_indicator_page_color = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int default_circle_indicator_stroke_color = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int default_title_indicator_footer_color = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int default_title_indicator_selected_color = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int default_title_indicator_text_color = 2130968599;
			
			// aapt resource value: 0x7f040008
			public const int dialog_theme_color = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int dialog_tr_theme_color = 2130968585;
			
			// aapt resource value: 0x7f040004
			public const int inet_bg_color = 2130968580;
			
			// aapt resource value: 0x7f040018
			public const int list_bg = 2130968600;
			
			// aapt resource value: 0x7f040005
			public const int list_selected = 2130968581;
			
			// aapt resource value: 0x7f040001
			public const int solid_blue = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int solid_green = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int solid_red = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int solid_yellow = 2130968579;
			
			// aapt resource value: 0x7f04000a
			public const int vpi__background_holo_dark = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int vpi__background_holo_light = 2130968587;
			
			// aapt resource value: 0x7f04000e
			public const int vpi__bright_foreground_disabled_holo_dark = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int vpi__bright_foreground_disabled_holo_light = 2130968591;
			
			// aapt resource value: 0x7f04000c
			public const int vpi__bright_foreground_holo_dark = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int vpi__bright_foreground_holo_light = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int vpi__bright_foreground_inverse_holo_dark = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int vpi__bright_foreground_inverse_holo_light = 2130968593;
			
			// aapt resource value: 0x7f040019
			public const int vpi__dark_theme = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int vpi__light_theme = 2130968602;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0000
			public const int default_circle_indicator_radius = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int default_circle_indicator_stroke_width = 2131361793;
			
			// aapt resource value: 0x7f0a0002
			public const int default_title_indicator_clip_padding = 2131361794;
			
			// aapt resource value: 0x7f0a0004
			public const int default_title_indicator_footer_indicator_height = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int default_title_indicator_footer_indicator_underline_padding = 2131361797;
			
			// aapt resource value: 0x7f0a0003
			public const int default_title_indicator_footer_line_height = 2131361795;
			
			// aapt resource value: 0x7f0a0006
			public const int default_title_indicator_footer_padding = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int default_title_indicator_text_size = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int default_title_indicator_title_padding = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int default_title_indicator_top_padding = 2131361801;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int app_sample_code = 2130837505;
			
			// aapt resource value: 0x7f020032
			public const int blue = 2130837554;
			
			// aapt resource value: 0x7f020002
			public const int boleto = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int border = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int cheque = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int cliente_item = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int cliente_item_pedido = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int cliente_item_pendencia = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int custom_tab_indicator = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int custom_tab_indicator_selected = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int custom_tab_indicator_selected_focused = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int custom_tab_indicator_selected_pressed = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int custom_tab_indicator_unselected = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int custom_tab_indicator_unselected_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int custom_tab_indicator_unselected_pressed = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int dinheiro = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int disponivel = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int entrada = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int excluir = 2130837522;
			
			// aapt resource value: 0x7f020033
			public const int green = 2130837555;
			
			// aapt resource value: 0x7f020013
			public const int ic_settings_applications = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int ic_settings_display = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int ic_tab_artists = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int ic_tab_artists_grey = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_tab_artists_white = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int img_carrinho = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int img_cliente = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int img_comunicacao = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int img_configuracao = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int img_financeiro = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int img_logoff = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int img_money = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int img_pesquisa = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int img_relatorio = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int img_remessa = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int img_sos = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int LogoInet = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ok = 2130837541;
			
			// aapt resource value: 0x7f020031
			public const int red = 2130837553;
			
			// aapt resource value: 0x7f020026
			public const int saida = 2130837542;
			
			// aapt resource value: 0x7f020035
			public const int screen_background_black = 2130837557;
			
			// aapt resource value: 0x7f020027
			public const int seta_direita = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int seta_esquerda = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int stat_sample = 2130837545;
			
			// aapt resource value: 0x7f020036
			public const int translucent_background = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int transparent_background = 2130837559;
			
			// aapt resource value: 0x7f02002a
			public const int vpi__tab_indicator = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int vpi__tab_selected_focused_holo = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int vpi__tab_selected_holo = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int vpi__tab_selected_pressed_holo = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int vpi__tab_unselected_focused_holo = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int vpi__tab_unselected_holo = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int vpi__tab_unselected_pressed_holo = 2130837552;
			
			// aapt resource value: 0x7f020034
			public const int yellow = 2130837556;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0037
			public const int btCliente = 2131492919;
			
			// aapt resource value: 0x7f0c003d
			public const int btConfigurar = 2131492925;
			
			// aapt resource value: 0x7f0c007d
			public const int btDiaAnterior = 2131492989;
			
			// aapt resource value: 0x7f0c007f
			public const int btDiaProximo = 2131492991;
			
			// aapt resource value: 0x7f0c003a
			public const int btLogoff = 2131492922;
			
			// aapt resource value: 0x7f0c0038
			public const int btPedidos = 2131492920;
			
			// aapt resource value: 0x7f0c003c
			public const int btRelatorio = 2131492924;
			
			// aapt resource value: 0x7f0c0039
			public const int btRemessa = 2131492921;
			
			// aapt resource value: 0x7f0c003b
			public const int btSincronizar = 2131492923;
			
			// aapt resource value: 0x7f0c003e
			public const int btVersao = 2131492926;
			
			// aapt resource value: 0x7f0c0069
			public const int btnAbrirDoc = 2131492969;
			
			// aapt resource value: 0x7f0c0082
			public const int btnAtualizarLista = 2131492994;
			
			// aapt resource value: 0x7f0c004d
			public const int btnBoleto = 2131492941;
			
			// aapt resource value: 0x7f0c0056
			public const int btnCancelarOc = 2131492950;
			
			// aapt resource value: 0x7f0c0083
			public const int btnClientesRoteiro = 2131492995;
			
			// aapt resource value: 0x7f0c004e
			public const int btnFecharPedidoFinalizado = 2131492942;
			
			// aapt resource value: 0x7f0c0051
			public const int btnFiltrar = 2131492945;
			
			// aapt resource value: 0x7f0c0050
			public const int btnFimFiltro = 2131492944;
			
			// aapt resource value: 0x7f0c0044
			public const int btnFinalizarPedido = 2131492932;
			
			// aapt resource value: 0x7f0c0066
			public const int btnFinalizarPesquisa = 2131492966;
			
			// aapt resource value: 0x7f0c0081
			public const int btnHoje = 2131492993;
			
			// aapt resource value: 0x7f0c004f
			public const int btnInicioFiltro = 2131492943;
			
			// aapt resource value: 0x7f0c0052
			public const int btnLimpar = 2131492946;
			
			// aapt resource value: 0x7f0c0065
			public const int btnLimparPesquisa = 2131492965;
			
			// aapt resource value: 0x7f0c0036
			public const int btnLogin = 2131492918;
			
			// aapt resource value: 0x7f0c004c
			public const int btnNotaFiscal = 2131492940;
			
			// aapt resource value: 0x7f0c0041
			public const int btnOC = 2131492929;
			
			// aapt resource value: 0x7f0c0055
			public const int btnOkOc = 2131492949;
			
			// aapt resource value: 0x7f0c0043
			public const int btnPagamento = 2131492931;
			
			// aapt resource value: 0x7f0c0042
			public const int btnProdutosSelecionados = 2131492930;
			
			// aapt resource value: 0x7f0c0070
			public const int btnRelPedFim = 2131492976;
			
			// aapt resource value: 0x7f0c006e
			public const int btnRelPedInicio = 2131492974;
			
			// aapt resource value: 0x7f0c0072
			public const int btnRelPedOrcGerar = 2131492978;
			
			// aapt resource value: 0x7f0c0079
			public const int btnRelQtdValor = 2131492985;
			
			// aapt resource value: 0x7f0c0078
			public const int btnRelQuantidades = 2131492984;
			
			// aapt resource value: 0x7f0c007a
			public const int btnRelVendas = 2131492986;
			
			// aapt resource value: 0x7f0c002b
			public const int btnSalvaConfiguracao = 2131492907;
			
			// aapt resource value: 0x7f0c006a
			public const int btnSelectPrinter = 2131492970;
			
			// aapt resource value: 0x7f0c004b
			public const int btnUploadPedido = 2131492939;
			
			// aapt resource value: 0x7f0c0023
			public const int chkComRoteiro = 2131492899;
			
			// aapt resource value: 0x7f0c0022
			public const int edtFiltro = 2131492898;
			
			// aapt resource value: 0x7f0c0000
			public const int horizontal = 2131492864;
			
			// aapt resource value: 0x7f0c0085
			public const int indicator = 2131492997;
			
			// aapt resource value: 0x7f0c0063
			public const int indicatorPesquisa = 2131492963;
			
			// aapt resource value: 0x7f0c0087
			public const int ivLogo = 2131492999;
			
			// aapt resource value: 0x7f0c0058
			public const int layoutChequeInfo = 2131492952;
			
			// aapt resource value: 0x7f0c007b
			public const int layoutDadosVendaGrupos = 2131492987;
			
			// aapt resource value: 0x7f0c002c
			public const int layoutItemDadosVenda = 2131492908;
			
			// aapt resource value: 0x7f0c000e
			public const int lbBairro = 2131492878;
			
			// aapt resource value: 0x7f0c0012
			public const int lbCep = 2131492882;
			
			// aapt resource value: 0x7f0c0010
			public const int lbCidade = 2131492880;
			
			// aapt resource value: 0x7f0c001a
			public const int lbDocumentoCliente = 2131492890;
			
			// aapt resource value: 0x7f0c001c
			public const int lbEmailCliente = 2131492892;
			
			// aapt resource value: 0x7f0c0018
			public const int lbNomeFantasiaCliente = 2131492888;
			
			// aapt resource value: 0x7f0c000c
			public const int lbNumeroEndereco = 2131492876;
			
			// aapt resource value: 0x7f0c0016
			public const int lbRazaoSocialCliente = 2131492886;
			
			// aapt resource value: 0x7f0c000a
			public const int lbRuaEndereco = 2131492874;
			
			// aapt resource value: 0x7f0c001e
			public const int lbTelefone = 2131492894;
			
			// aapt resource value: 0x7f0c0008
			public const int lineQuantidade = 2131492872;
			
			// aapt resource value: 0x7f0c0076
			public const int lineQuantidadeValor = 2131492982;
			
			// aapt resource value: 0x7f0c0068
			public const int linearLayout1 = 2131492968;
			
			// aapt resource value: 0x7f0c0024
			public const int lvCliente = 2131492900;
			
			// aapt resource value: 0x7f0c007c
			public const int lvGruposQuantidadeValor = 2131492988;
			
			// aapt resource value: 0x7f0c0033
			public const int lvModal = 2131492915;
			
			// aapt resource value: 0x7f0c0053
			public const int lvPedidos = 2131492947;
			
			// aapt resource value: 0x7f0c0020
			public const int lvPendencia = 2131492896;
			
			// aapt resource value: 0x7f0c0040
			public const int lvProduto = 2131492928;
			
			// aapt resource value: 0x7f0c004a
			public const int lvProdutosPedido = 2131492938;
			
			// aapt resource value: 0x7f0c0061
			public const int lvProdutosSelecionados = 2131492961;
			
			// aapt resource value: 0x7f0c0005
			public const int lvRemessasAcerto = 2131492869;
			
			// aapt resource value: 0x7f0c0084
			public const int lvRoteiro = 2131492996;
			
			// aapt resource value: 0x7f0c008e
			public const int menuFinalizaPedido = 2131493006;
			
			// aapt resource value: 0x7f0c008f
			public const int menuProdutosSelecionados = 2131493007;
			
			// aapt resource value: 0x7f0c0060
			public const int netQtdSolicitada = 2131492960;
			
			// aapt resource value: 0x7f0c0002
			public const int none = 2131492866;
			
			// aapt resource value: 0x7f0c0086
			public const int pager = 2131492998;
			
			// aapt resource value: 0x7f0c0064
			public const int pagerPesquisa = 2131492964;
			
			// aapt resource value: 0x7f0c0088
			public const int pbInicio = 2131493000;
			
			// aapt resource value: 0x7f0c008d
			public const int rbBonificacao = 2131493005;
			
			// aapt resource value: 0x7f0c0014
			public const int rbPessoaFisica = 2131492884;
			
			// aapt resource value: 0x7f0c0015
			public const int rbPessoaJuridica = 2131492885;
			
			// aapt resource value: 0x7f0c008c
			public const int rbVenda = 2131493004;
			
			// aapt resource value: 0x7f0c003f
			public const int snGrupo = 2131492927;
			
			// aapt resource value: 0x7f0c0057
			public const int snTipoPagamento = 2131492951;
			
			// aapt resource value: 0x7f0c0089
			public const int tabBottomLayout = 2131493001;
			
			// aapt resource value: 0x7f0c0073
			public const int tbTemplate = 2131492979;
			
			// aapt resource value: 0x7f0c0074
			public const int tbValorTemplate = 2131492980;
			
			// aapt resource value: 0x7f0c0006
			public const int tbVisaoGrupo = 2131492870;
			
			// aapt resource value: 0x7f0c008a
			public const int tlModal = 2131493002;
			
			// aapt resource value: 0x7f0c008b
			public const int trHeader = 2131493003;
			
			// aapt resource value: 0x7f0c0009
			public const int trQuantidadeDetail = 2131492873;
			
			// aapt resource value: 0x7f0c0007
			public const int trQuantidadeHeader = 2131492871;
			
			// aapt resource value: 0x7f0c0077
			public const int trQuantidadeValorDetail = 2131492983;
			
			// aapt resource value: 0x7f0c0075
			public const int trQuantidadeValorHeader = 2131492981;
			
			// aapt resource value: 0x7f0c005b
			public const int trValorCheque = 2131492955;
			
			// aapt resource value: 0x7f0c0003
			public const int triangle = 2131492867;
			
			// aapt resource value: 0x7f0c0062
			public const int tvClientePesquisa = 2131492962;
			
			// aapt resource value: 0x7f0c007e
			public const int tvDia = 2131492990;
			
			// aapt resource value: 0x7f0c0021
			public const int tvFiltro = 2131492897;
			
			// aapt resource value: 0x7f0c0025
			public const int tvMsgSemCliente = 2131492901;
			
			// aapt resource value: 0x7f0c0046
			public const int tvNumeroPedido = 2131492934;
			
			// aapt resource value: 0x7f0c0047
			public const int tvOC = 2131492935;
			
			// aapt resource value: 0x7f0c0054
			public const int tvOc = 2131492948;
			
			// aapt resource value: 0x7f0c0080
			public const int tvPasta = 2131492992;
			
			// aapt resource value: 0x7f0c005e
			public const int tvProdutoNome = 2131492958;
			
			// aapt resource value: 0x7f0c006b
			public const int tvQtdPedida = 2131492971;
			
			// aapt resource value: 0x7f0c002f
			public const int tvQuantidadeDisponivel = 2131492911;
			
			// aapt resource value: 0x7f0c0048
			public const int tvQuantidadePedidoFinalizado = 2131492936;
			
			// aapt resource value: 0x7f0c002d
			public const int tvQuantidadeRecebida = 2131492909;
			
			// aapt resource value: 0x7f0c002e
			public const int tvQuantidadeVendida = 2131492910;
			
			// aapt resource value: 0x7f0c005f
			public const int tvQuantidades = 2131492959;
			
			// aapt resource value: 0x7f0c0045
			public const int tvResultadoPedido = 2131492933;
			
			// aapt resource value: 0x7f0c006d
			public const int tvTitulo = 2131492973;
			
			// aapt resource value: 0x7f0c005d
			public const int tvTotal = 2131492957;
			
			// aapt resource value: 0x7f0c005a
			public const int tvTotalDesconto = 2131492954;
			
			// aapt resource value: 0x7f0c0059
			public const int tvTotalSelecionado = 2131492953;
			
			// aapt resource value: 0x7f0c0049
			public const int tvTotalValorFinalizado = 2131492937;
			
			// aapt resource value: 0x7f0c005c
			public const int tvValorCheque = 2131492956;
			
			// aapt resource value: 0x7f0c006c
			public const int tvValorPedido = 2131492972;
			
			// aapt resource value: 0x7f0c0032
			public const int tvValorTotalBoleto = 2131492914;
			
			// aapt resource value: 0x7f0c0031
			public const int tvValorTotalCheque = 2131492913;
			
			// aapt resource value: 0x7f0c0030
			public const int tvValorTotalDinheiro = 2131492912;
			
			// aapt resource value: 0x7f0c000f
			public const int txtBairro = 2131492879;
			
			// aapt resource value: 0x7f0c0013
			public const int txtCep = 2131492883;
			
			// aapt resource value: 0x7f0c0027
			public const int txtChaveIntegracao = 2131492903;
			
			// aapt resource value: 0x7f0c0011
			public const int txtCidade = 2131492881;
			
			// aapt resource value: 0x7f0c0029
			public const int txtCnpjEmpresa = 2131492905;
			
			// aapt resource value: 0x7f0c0028
			public const int txtCodigoTabelaPreco = 2131492904;
			
			// aapt resource value: 0x7f0c001b
			public const int txtDocumentoCliente = 2131492891;
			
			// aapt resource value: 0x7f0c001d
			public const int txtEmailCliente = 2131492893;
			
			// aapt resource value: 0x7f0c002a
			public const int txtIndiceDia = 2131492906;
			
			// aapt resource value: 0x7f0c0019
			public const int txtNomeFantasiaCliente = 2131492889;
			
			// aapt resource value: 0x7f0c000d
			public const int txtNumeroEndereco = 2131492877;
			
			// aapt resource value: 0x7f0c0017
			public const int txtRazaoSocialCliente = 2131492887;
			
			// aapt resource value: 0x7f0c0071
			public const int txtRelPedOrcDataFim = 2131492977;
			
			// aapt resource value: 0x7f0c006f
			public const int txtRelPedOrcDataInicio = 2131492975;
			
			// aapt resource value: 0x7f0c000b
			public const int txtRuaEndereco = 2131492875;
			
			// aapt resource value: 0x7f0c0035
			public const int txtSenha = 2131492917;
			
			// aapt resource value: 0x7f0c001f
			public const int txtTelefone = 2131492895;
			
			// aapt resource value: 0x7f0c0026
			public const int txtUrlWeb = 2131492902;
			
			// aapt resource value: 0x7f0c0034
			public const int txtUsuario = 2131492916;
			
			// aapt resource value: 0x7f0c0004
			public const int underline = 2131492868;
			
			// aapt resource value: 0x7f0c0001
			public const int vertical = 2131492865;
			
			// aapt resource value: 0x7f0c0067
			public const int wvDocument = 2131492967;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int default_circle_indicator_orientation = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int default_title_indicator_footer_indicator_style = 2131296257;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AcertoSaldo = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ClienteDetailEndereco = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ClienteDetailGeral = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int ClienteDetailPendencia = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int ClienteList = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Configuracao = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int ItemDadosVenda = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int ListModal = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Login = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int MenuFragment_00 = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int MenuFragment_01 = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int Pedido = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int PedidoFinalizado = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int PedidoList = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int PedidoOC = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int PedidoPagamento = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int PedidoSelecaoItem = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int PedidoSelecionado = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Pesquisa = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Print = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int ProdutoSelecionadoItem = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int RelatorioPedidoOrcamento = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int RelatorioQuantidadeTemplate = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int RelatorioQuantidadeValorTemplate = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Relatorios = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int RelatorioSinteticoForcaVenda = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Roteiro = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int simple_spinner_item = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int SplashScreen = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int TabFragment = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int TabLayout = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int TableModal = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int Teste = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int TipoPedidoSelecao = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int vpi__tab = 2130903075;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int MenuPedido = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int alert_dialog_cancel = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int alert_dialog_no = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int alert_dialog_ok = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int alert_dialog_yes = 2131034114;
			
			// aapt resource value: 0x7f05000b
			public const int comunicao_expirou = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int dia_boleto_prompt = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int grupo_prompt = 2131034116;
			
			// aapt resource value: 0x7f050009
			public const int relatorio_cliente_devedores = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int relatorio_faturamento_categorio_produto = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int relatorio_pedido_orcamento = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int relatorio_saldo_estoque = 2131034122;
			
			// aapt resource value: 0x7f050005
			public const int tipo_pagamento_prompt = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070007
			public const int CustomCirclePageIndicator = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int CustomTitlePageIndicator = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int DialogModal = 2131165189;
			
			// aapt resource value: 0x7f070000
			public const int INetTheme = 2131165184;
			
			// aapt resource value: 0x7f070012
			public const int TextAppearance_TabPageIndicator = 2131165202;
			
			// aapt resource value: 0x7f07000c
			public const int Theme_PageIndicatorDefaults = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int Widget = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int Widget_CirclePageIndicator = 2131165198;
			
			// aapt resource value: 0x7f070010
			public const int Widget_TabPageIndicator = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int Widget_TabPageIndicator_Text = 2131165201;
			
			// aapt resource value: 0x7f07000f
			public const int Widget_TitlePageIndicator = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int WindowTitleBackground = 2131165188;
			
			// aapt resource value: 0x7f070008
			public const int customtabpageindicator = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int customtabpageindicator_text = 2131165193;
			
			// aapt resource value: 0x7f070001
			public const int groupbox = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int groupboxContent = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int groupboxLabel = 2131165187;
			
			// aapt resource value: 0x7f07000a
			public const int input_filter = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int label_input = 2131165195;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CirclePageIndicator = new int[] {
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980};
			
			// aapt resource value: 0
			public const int CirclePageIndicator_centered = 0;
			
			// aapt resource value: 1
			public const int CirclePageIndicator_fillColor = 1;
			
			// aapt resource value: 3
			public const int CirclePageIndicator_orientation = 3;
			
			// aapt resource value: 2
			public const int CirclePageIndicator_pageColor = 2;
			
			// aapt resource value: 4
			public const int CirclePageIndicator_radius = 4;
			
			// aapt resource value: 5
			public const int CirclePageIndicator_snap = 5;
			
			// aapt resource value: 6
			public const int CirclePageIndicator_strokeColor = 6;
			
			// aapt resource value: 7
			public const int CirclePageIndicator_strokeWidth = 7;
			
			public static int[] TitlePageIndicator = new int[] {
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993};
			
			// aapt resource value: 0
			public const int TitlePageIndicator_clipPadding = 0;
			
			// aapt resource value: 1
			public const int TitlePageIndicator_footerColor = 1;
			
			// aapt resource value: 4
			public const int TitlePageIndicator_footerIndicatorHeight = 4;
			
			// aapt resource value: 3
			public const int TitlePageIndicator_footerIndicatorStyle = 3;
			
			// aapt resource value: 5
			public const int TitlePageIndicator_footerIndicatorUnderlinePadding = 5;
			
			// aapt resource value: 2
			public const int TitlePageIndicator_footerLineHeight = 2;
			
			// aapt resource value: 6
			public const int TitlePageIndicator_footerPadding = 6;
			
			// aapt resource value: 8
			public const int TitlePageIndicator_selectedBold = 8;
			
			// aapt resource value: 7
			public const int TitlePageIndicator_selectedColor = 7;
			
			// aapt resource value: 9
			public const int TitlePageIndicator_textColor = 9;
			
			// aapt resource value: 10
			public const int TitlePageIndicator_textSize = 10;
			
			// aapt resource value: 11
			public const int TitlePageIndicator_titlePadding = 11;
			
			// aapt resource value: 12
			public const int TitlePageIndicator_topPadding = 12;
			
			public static int[] ViewPagerIndicator = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972};
			
			// aapt resource value: 0
			public const int ViewPagerIndicator_vpiCirclePageIndicatorStyle = 0;
			
			// aapt resource value: 3
			public const int ViewPagerIndicator_vpiPageTheme = 3;
			
			// aapt resource value: 2
			public const int ViewPagerIndicator_vpiTabPageIndicatorStyle = 2;
			
			// aapt resource value: 4
			public const int ViewPagerIndicator_vpiTabTextStyle = 4;
			
			// aapt resource value: 1
			public const int ViewPagerIndicator_vpiTitlePageIndicatorStyle = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
